name: First Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code 
        uses: actions/checkout@v4

      - name: Hello
        run: echo "hello github actions"

      - name: Check repository files
        run: ls -al

      - name: Runner Information
        run: | 
          hostname
          whoami
          pwd 
          uname -a